import { Linkedin, Github, Mail } from "lucide-react";

export const config = {
  settings: {
    fallbackImage:
      "https://raw.githubusercontent.com/lorenzopalaia/Repo-Template/main/repo_assets/preview.png",
    name: "Lorenzo Palaia",
    title: "Software Engineer | Computer and Automatic Engineer Graduate",
    description:
      "Crypto enthusiast, passionate about programming, artificial intelligence, blockchain, finance and traveling. Computer and Automatic Engineering graduate at Sapienza University of Rome. Currently working as a freelance fullstack developer.",
    keywords: [
      "Lorenzo Palaia",
      "Software Engineer Rome",
      "Computer Engineer Italy",
      "Automatic Engineering graduate",
      "Fullstack developer freelance",
      "Python developer Rome",
      "Blockchain expert Italy",
      "AI enthusiast programmer",
      "Cryptocurrency developer",
      "Travel tech expert",
      "Arduino projects",
      "Neural Style Transfer",
      "Genre Classification AI",
      "Tensorflow projects",
      "Vue.js developer",
      "Node.js expert",
      "MongoDB developer",
      "PostgreSQL skills",
      "Sapienza University graduate",
      "Italian software engineer",
      "English speaking programmer",
      "French speaking developer",
      "GitHub projects portfolio",
      "LinkedIn tech professional",
      "Twitter tech influencer",
      "Crypto tracking app",
      "YOLO object detection",
      "UAV software engineer",
      "Computer Vision specialist",
      "Flask API developer",
      "Next.js portfolio website",
      "Tailwind CSS expert",
      "Vercel deployment",
      "Inter typeface design",
      "C programming skills",
      "Java developer Italy",
      "JavaScript fullstack",
      "HTML5 CSS3 expert",
      "Randstad AI Hackathon",
      "AUVSI SUAS competition",
      "Sapienza Flight Team",
      "Terrain mapping systems",
      "EfficientNet models",
      "Custom dataset training",
      "Data structures algorithms",
      "Software design patterns",
      "Parallel computing expert",
      "Electronics programming",
      "Web development portfolio",
      "Cryptocurrency enthusiast",
      "Finance tech integration",
      "Travel tech solutions",
      "Gamification in projects",
      "Arduino oscilloscope",
      "Blocktracr cryptocurrency",
      "Neural network job classifier",
      "Word2Vec implementation",
      "Bag of Words technique",
      "F1 score optimization",
      "Chart.js data visualization",
      "CCXT API integration",
      "MEVN stack projects",
      "Valgrind memory management",
      "Serial communication Arduino",
      "GitHub API integration",
      "Server-side caching",
      "Custom React hooks",
      "UI/UX principles",
      "Scala programming",
      "Assembly language skills",
      "Italian tech professional",
      "CEFR B2 English developer",
      "Crypto market data analysis",
      "Spectogram audio processing",
      "Data augmentation techniques",
      "Continuous integration",
      "Buffered sampling Arduino",
      "Schematic design electronics",
      "Job description classification",
      "Team collaboration tools",
      "Technical writing skills",
      "Open-source contributions",
      "Cross-platform development",
      "Mobile-responsive design",
      "SEO optimization techniques",
      "Performance optimization",
      "Code refactoring expert",
      "Agile methodology",
      "Scrum framework",
      "DevOps practices",
      "Cloud computing solutions",
      "Microservices architecture",
      "RESTful API design",
      "GraphQL implementation",
      "Cybersecurity awareness",
      "IoT project experience",
      "Machine learning applications",
      "Natural language processing",
      "Big data analysis",
      "Quantum computing interest",
      "Fullstack web developer",
      "AI researcher Italy",
      "Blockchain technology expert",
      "Cryptocurrency market analyst",
      "Travel tech innovator",
      "Arduino project designer",
      "Neural network architect",
      "TensorFlow implementation specialist",
      "Vue.js frontend developer",
      "Node.js backend expert",
      "NoSQL database specialist",
      "SQL database expert",
      "Rome-based software engineer",
      "Multilingual programmer",
      "Tech project showcase",
      "Professional network IT",
      "Social media tech presence",
      "Cryptocurrency portfolio tracker",
      "Computer vision AI developer",
      "Unmanned Aerial Vehicle programmer",
      "REST API designer",
      "Modern web technologies",
      "CSS framework specialist",
      "Cloud deployment expert",
      "Typography in web design",
      "Low-level programming expert",
      "Enterprise Java developer",
      "Frontend JavaScript specialist",
      "Web standards compliance",
      "AI competition participant",
      "Drone software developer",
      "3D terrain visualization",
      "Deep learning model training",
      "Algorithm optimization specialist",
      "Software architecture expert",
      "High-performance computing",
      "Embedded systems programmer",
      "Full-stack web portfolio",
      "Blockchain finance integration",
      "Tech-enhanced travel solutions",
      "Game mechanics in software",
      "DIY electronics projects",
      "Crypto market data visualization",
      "Machine learning for HR",
      "NLP techniques implementation",
      "Text classification AI",
      "Performance metrics optimization",
      "Financial data visualization",
      "Cryptocurrency exchange API",
      "Full-stack JavaScript developer",
      "Memory leak detection",
      "Microcontroller communication",
      "Third-party API integration",
      "Web performance optimization",
      "React custom hook developer",
      "User experience designer",
      "Functional programming Scala",
      "Low-level system programmer",
      "Polyglot developer Italy",
      "Advanced English tech communication",
      "Cryptocurrency data analyst",
      "Audio signal processing AI",
      "Machine learning data preparation",
      "Continuous delivery pipeline",
      "Digital signal processing",
      "PCB design for electronics",
      "AI for recruitment",
      "Remote collaboration expert",
      "Technical documentation specialist",
      "GitHub open source contributor",
      "Hybrid app development",
      "Responsive web design expert",
      "Search engine optimization",
      "Web app performance tuning",
      "Legacy code modernization",
      "Agile software development",
      "Sprint planning and execution",
      "CI/CD pipeline setup",
      "Serverless architecture",
      "Distributed systems design",
      "API-first development",
      "Modern query language implementation",
      "Information security in software",
      "Internet of Things developer",
      "AI model deployment",
      "Text analysis with NLP",
      "Large-scale data processing",
      "Emerging compute technologies",
      "Rome tech scene",
      "Italian startup ecosystem",
      "European tech innovator",
      "Computer science researcher",
      "AI ethics awareness",
      "Blockchain for business",
      "Crypto economic models",
      "Adventure travel tech",
      "Maker movement participant",
      "Audio AI researcher",
      "Computer vision applications",
      "Deep learning frameworks",
      "Frontend framework expert",
      "Backend scalability specialist",
      "Database performance tuning",
      "RDBMS optimization",
      "Software engineering best practices",
      "Polyglot coding skills",
      "Tech blog writer",
      "IT industry networker",
      "Developer community leader",
      "Fintech application developer",
      "Object detection algorithms",
      "Autonomous systems programmer",
      "API documentation specialist",
      "Progressive web apps",
      "UI animation with CSS",
      "Serverless deployment",
      "Web typography expert",
      "Systems programming languages",
      "Enterprise software architect",
      "Single-page application developer",
      "Web accessibility advocate",
      "Hackathon mentor",
      "Aerospace software engineer",
      "GIS data visualization",
      "Neural network optimization",
      "Competitive programming",
      "Design patterns implementer",
      "Grid computing systems",
      "IoT device programmer",
      "Full-stack web architect",
      "DeFi platform developer",
      "Smart contract auditor",
      "Tech-enabled travel planner",
      "Gamification strategist",
      "Open hardware enthusiast",
      "Crypto analytics developer",
      "NLP model trainer",
      "Text mining expert",
      "Algorithm efficiency analyst",
      "Financial modeling with code",
      "Crypto exchange integrator",
      "Isomorphic JavaScript developer",
      "Memory profiling tools",
      "Real-time systems programmer",
      "OAuth implementation specialist",
      "Frontend performance optimizer",
      "React state management expert",
      "Interaction design principles",
      "JVM languages programmer",
      "Assembly optimization techniques",
      "Cross-cultural tech communicator",
      "Technical English proficiency",
      "Blockchain data analyst",
      "Music AI researcher",
      "Data augmentation strategist",
      "DevOps automation expert",
      "Embedded Linux developer",
      "Circuit design hobbyist",
      "HR tech innovator",
      "Agile team collaborator",
      "API documentation writer",
      "Open-source project maintainer",
      "Progressive web app developer",
      "Mobile-first design advocate",
      "Technical SEO specialist",
      "Web vitals optimization",
      "Software modernization consultant",
      "Kanban methodology practitioner",
      "Extreme Programming (XP) advocate",
      "Jenkins pipeline developer",
      "AWS solutions architect",
      "Microservices design patterns",
      "OpenAPI specification expert",
      "GraphQL schema designer",
      "Penetration testing awareness",
      "MQTT protocol implementation",
      "TensorFlow.js developer",
      "BERT model fine-tuning",
      "Hadoop ecosystem familiarity",
      "Quantum algorithms enthusiast",
      "Italian tech conference speaker",
      "EU tech policy follower",
      "Computer ethics discussant",
      "DLT use case researcher",
      "Tokenomics analyst",
      "Digital nomad tech solutions",
      "3D printing enthusiast",
      "Voice AI applications",
      "Facial recognition ethics",
      "PyTorch model developer",
      "Svelte.js explorer",
      "Deno runtime experimenter",
      "Time-series database expert",
      "Graph database implementer",
      "Clean code advocate",
      "Polyglot persistence architect",
      "Tech tutorial creator",
      "Stack Overflow contributor",
      "Crypto wallet developer",
      "SLAM algorithm implementer",
      "Swarm robotics programmer",
      "OpenAPI code generator",
      "Jamstack architecture",
      "WebGL graphics programmer",
      "Edge computing solutions",
      "Web font performance optimizer",
      "RISC-V architecture enthusiast",
      "Microservices deployment strategies",
      "WebAssembly applications",
      "WCAG compliance expert",
      "Algorithm competition judge",
      "Satellite software developer",
      "LiDAR data processing",
      "Federated learning researcher",
      "Competitive coding coach",
      "Hexagonal architecture implementer",
      "GPGPU computing",
      "LoRaWAN network developer",
      "Decentralized web advocate",
      "Zero-knowledge proof implementer",
      "NFT marketplace developer",
      "AR travel app creator",
      "Serious games developer",
      "FPGAs for AI acceleration",
      "Crypto arbitrage bot developer",
      "Sentiment analysis model trainer",
      "Topic modeling expert",
      "Algorithm visualization creator",
      "Quant trading strategies coder",
      "DEX smart contract developer",
      "Universal JavaScript apps",
      "WebSocket real-time apps",
      "Bare-metal programming",
      "OAuth 2.0 server implementer",
      "Core Web Vitals optimizer",
      "Redux middleware developer",
      "Micro-interactions designer",
      "Clojure web services",
      "SIMD parallelism expert",
      "Technical debt reducer",
      "Business English for IT",
      "Crypto forensics analyst",
      "Generative AI for music",
      "GAN model architect",
      "GitOps workflow implementer",
      "RTOS developer",
      "IoT security specialist",
      "AI recruitment tool developer",
      "Remote pair programming advocate",
      "AsyncAPI specification writer",
      "Inner source champion",
      "AMP website developer",
      "Inclusive design practitioner",
      "Lighthouse score optimizer",
      "Web performance budgeting",
      "DDD practitioner",
      "SAFe framework knowledge",
      "Terraform infrastructure as code",
      "Google Cloud Platform solutions",
      "Service mesh implementation",
      "gRPC services developer",
      "JWT authentication expert",
      "OWASP security practices",
      "BLE protocol developer",
      "Keras model deployment",
      "NLTK library expert",
      "Apache Spark big data processing",
      "Quantum cryptography interest",
      "European tech ethics advocate",
      "Blockchain governance models",
      "Sustainable tech practices",
      "Virtual reality developer",
      "Autonomous drone programmer",
      "Edge AI implementer",
      "FastAPI backend developer",
      "WebRTC applications",
      "Rust for web development",
      "Time-series forecasting",
      "Knowledge graph developer",
      "TDD evangelist",
      "Event-driven architecture",
      "Developer relations",
      "Hackathon organizer",
      "DApp frontend developer",
      "Visual SLAM implementation",
      "Swarm intelligence algorithms",
      "API-first design advocate",
      "Static site generator expert",
      "Three.js 3D web developer",
      "Fog computing architect",
      "Web performance monitoring",
      "WASM for performance",
      "Micro-frontend architecture",
      "A11Y testing automation",
      "Coding bootcamp instructor",
      "CubeSat software developer",
      "Point cloud processing",
      "Transfer learning specialist",
      "Competitive programming platform",
      "Event sourcing implementation",
      "Quantum machine learning",
      "Zigbee protocol developer",
      "IPFS application developer",
      "zk-SNARK implementation",
      "Metaverse developer",
      "VR tourism app creator",
      "Blockchain gaming developer",
      "AI art generator",
      "High-frequency trading systems",
      "Anomaly detection models",
      "Chatbot developer with NLU",
      "Algorithm animator",
      "Options pricing model developer",
      "Layer 2 blockchain solutions",
      "Isomorphic rendering expert",
      "P2P networking protocols",
      "Kernel module developer",
      "SSO implementation specialist",
      "Web Vitals improvement strategies",
      "Zustand state management",
      "Micro-animations in UX",
      "Logic programming in Prolog",
      "GPU shader programming",
      "Code quality metrics analyst",
      "Technical presenter IT conferences",
      "Blockchain supply chain solutions",
      "AI-generated music composer",
      "Adversarial AI researcher",
      "MLOps pipeline architect",
      "Hyperledger Fabric developer",
      "Industrial IoT solutions",
      "AI ethics committee member",
      "Distributed team productivity",
      "API style guide author",
      "Innersource best practices",
      "PWA with offline capabilities",
      "Accessible rich internet applications",
      "Core Web Vitals consultant",
      "Web performance culture advocate",
      "CQRS pattern implementer",
      "LeSS framework experience",
      "Ansible automation scripts",
      "Azure cloud architect",
      "Istio service mesh expert",
      "Protocol buffers developer",
      "OAuth 2.0 flows implementer",
      "DevSecOps practices",
      "Thread protocol for IoT",
      "ONNX model converter",
      "spaCy NLP library expert",
      "Databricks platform user",
      "Post-quantum cryptography",
      "Tech diversity advocate",
      "DAO governance implementer",
      "Green software engineering",
      "Mixed reality developer",
      "Computer vision for drones",
      "TinyML developer",
      "Elixir backend services",
      "WebXR experience creator",
      "Go language web services",
      "Probabilistic data structures",
      "Neo4j graph database expert",
      "BDD with Cucumber",
      "CQRS with event sourcing",
      "Developer advocate",
      "Tech podcast host",
      "Software Engineering",
      "Python",
      "JavaScript",
      "Java",
      "C++",
      "C#",
      "Ruby",
      "PHP",
      "Go",
      "Rust",
      "Swift",
      "Kotlin",
      "TypeScript",
      "Scala",
      "Haskell",
      "Erlang",
      "Clojure",
      "F#",
      "COBOL",
      "Assembly",
      "Machine Learning",
      "Artificial Intelligence",
      "Deep Learning",
      "Natural Language Processing",
      "Computer Vision",
      "Data Science",
      "Big Data",
      "Data Analytics",
      "Data Visualization",
      "Database Management",
      "SQL",
      "NoSQL",
      "MongoDB",
      "PostgreSQL",
      "MySQL",
      "Oracle",
      "SQLite",
      "Redis",
      "Cassandra",
      "Neo4j",
      "Elasticsearch",
      "Web Development",
      "Frontend Development",
      "Backend Development",
      "Full Stack Development",
      "HTML",
      "CSS",
      "SASS",
      "LESS",
      "Bootstrap",
      "Tailwind CSS",
      "Material-UI",
      "React",
      "Angular",
      "Vue.js",
      "Svelte",
      "jQuery",
      "Node.js",
      "Express.js",
      "Django",
      "Flask",
      "Ruby on Rails",
      "ASP.NET",
      "Spring Boot",
      "Laravel",
      "Symfony",
      "CodeIgniter",
      "Gatsby",
      "Next.js",
      "Nuxt.js",
      "GraphQL",
      "RESTful API",
      "SOAP",
      "Microservices",
      "Serverless Architecture",
      "Container",
      "Docker",
      "Kubernetes",
      "AWS",
      "Azure",
      "Google Cloud Platform",
      "Heroku",
      "DigitalOcean",
      "Linode",
      "Netlify",
      "Vercel",
      "CI/CD",
      "Jenkins",
      "Travis CI",
      "CircleCI",
      "GitLab CI",
      "GitHub Actions",
      "Ansible",
      "Terraform",
      "Puppet",
      "Chef",
      "Kubernetes",
      "Istio",
      "Service Mesh",
      "Prometheus",
      "Grafana",
      "ELK Stack",
      "Splunk",
      "New Relic",
      "DataDog",
      "AppDynamics",
      "Dynatrace",
      "Version Control",
      "Git",
      "Subversion",
      "Mercurial",
      "GitHub",
      "GitLab",
      "Bitbucket",
      "Agile Methodology",
      "Scrum",
      "Kanban",
      "Extreme Programming",
      "Lean Software Development",
      "DevOps",
      "SRE",
      "TDD",
      "BDD",
      "DDD",
      "SOLID Principles",
      "Design Patterns",
      "Microservices",
      "Monolithic Architecture",
      "Event-Driven Architecture",
      "CQRS",
      "Event Sourcing",
      "Reactive Programming",
      "Functional Programming",
      "Object-Oriented Programming",
      "Aspect-Oriented Programming",
      "Concurrent Programming",
      "Parallel Programming",
      "Distributed Systems",
      "Blockchain",
      "Cryptocurrency",
      "Smart Contracts",
      "Ethereum",
      "Hyperledger",
      "Solidity",
      "Internet of Things",
      "Edge Computing",
      "Fog Computing",
      "5G",
      "WebAssembly",
      "Progressive Web Apps",
      "Single Page Applications",
      "Responsive Web Design",
      "Mobile App Development",
      "iOS Development",
      "Android Development",
      "React Native",
      "Flutter",
      "Xamarin",
      "Ionic",
      "PhoneGap",
      "Unity",
      "Unreal Engine",
      "Game Development",
      "Augmented Reality",
      "Virtual Reality",
      "Mixed Reality",
      "3D Modeling",
      "Computer Graphics",
      "Ray Tracing",
      "Quantum Computing",
      "Cybersecurity",
      "Penetration Testing",
      "Ethical Hacking",
      "Cryptography",
      "Network Security",
      "Information Security",
      "Biometrics",
      "Cloud Security",
      "DevSecOps",
      "OWASP",
      "Agile",
      "Scrum Master",
      "Product Owner",
      "Sprint Planning",
      "Daily Stand-up",
      "Sprint Review",
      "Sprint Retrospective",
      "Backlog Refinement",
      "User Stories",
      "Acceptance Criteria",
      "Burndown Chart",
      "Velocity",
      "Story Points",
      "Continuous Integration",
      "Continuous Delivery",
      "Continuous Deployment",
      "Blue-Green Deployment",
      "Canary Deployment",
      "A/B Testing",
      "Feature Flags",
      "Code Review",
      "Pair Programming",
      "Mob Programming",
      "Code Smells",
      "Refactoring",
      "Technical Debt",
      "Clean Code",
      "Code Coverage",
      "Static Code Analysis",
      "Dynamic Code Analysis",
      "Linting",
      "Unit Testing",
      "Integration Testing",
      "Functional Testing",
      "End-to-End Testing",
      "Acceptance Testing",
      "Performance Testing",
      "Load Testing",
      "Stress Testing",
      "Usability Testing",
      "Accessibility Testing",
      "Security Testing",
      "Regression Testing",
      "Smoke Testing",
      "Sanity Testing",
      "Exploratory Testing",
      "Mocking",
      "Stubbing",
      "Test-Driven Development",
      "Behavior-Driven Development",
      "Domain-Driven Design",
      "Event Storming",
      "User Experience (UX)",
      "User Interface (UI)",
      "Wireframing",
      "Prototyping",
      "Figma",
      "Sketch",
      "Adobe XD",
      "InVision",
      "Zeplin",
      "Design Systems",
      "Atomic Design",
      "Material Design",
      "Flat Design",
      "Skeuomorphism",
      "Responsive Design",
      "Mobile-First Design",
      "Accessibility (a11y)",
      "WCAG",
      "Section 508",
      "Screen Readers",
      "Color Contrast",
      "Semantic HTML",
      "WAI-ARIA",
      "Performance Optimization",
      "Lazy Loading",
      "Code Splitting",
      "Tree Shaking",
      "Minification",
      "Compression",
      "Caching",
      "CDN",
      "HTTP/2",
      "HTTP/3",
      "WebSockets",
      "Server-Sent Events",
      "Progressive Enhancement",
      "Graceful Degradation",
      "Cross-Browser Compatibility",
      "Polyfills",
      "Transpilation",
      "Babel",
      "Webpack",
      "Rollup",
      "Parcel",
      "ESLint",
      "Prettier",
      "Stylelint",
      "Husky",
      "Commitlint",
      "Conventional Commits",
      "Semantic Versioning",
      "npm",
      "Yarn",
      "pnpm",
      "Lerna",
      "Monorepo",
      "Microfrontends",
      "Module Federation",
      "Web Components",
      "Shadow DOM",
      "Custom Elements",
      "HTML Templates",
      "Storybook",
      "Design Tokens",
      "CSS-in-JS",
      "CSS Modules",
      "PostCSS",
      "BEM",
      "SMACSS",
      "OOCSS",
      "Grid Layout",
      "Flexbox",
      "CSS Variables",
      "CSS Animations",
      "CSS Transitions",
      "SVG",
      "Canvas",
      "WebGL",
      "Three.js",
      "D3.js",
      "Chart.js",
      "Highcharts",
      "Recharts",
      "Leaflet",
      "Mapbox",
      "OpenLayers",
      "WebRTC",
      "Socket.io",
      "Firebase",
      "Supabase",
      "Auth0",
      "JWT",
      "OAuth",
      "OpenID Connect",
      "SAML",
      "Single Sign-On",
      "Two-Factor Authentication",
      "Biometric Authentication",
      "Password Hashing",
      "HTTPS",
      "TLS",
      "SSL",
      "Public Key Infrastructure",
      "Digital Signatures",
      "Encryption",
      "Tokenization",
      "Data Masking",
      "GDPR",
      "CCPA",
      "HIPAA",
      "PCI DSS",
      "SOC 2",
      "ISO 27001",
      "NIST",
      "Threat Modeling",
      "Risk Assessment",
      "Vulnerability Management",
      "Incident Response",
      "Disaster Recovery",
      "Business Continuity",
      "Chaos Engineering",
      "Site Reliability Engineering",
      "Observability",
      "Monitoring",
      "Alerting",
      "Log Management",
      "Tracing",
      "APM",
      "RUM",
      "Synthetic Monitoring",
      "Capacity Planning",
      "Performance Budgets",
      "SLO",
      "SLI",
      "SLA",
      "Error Budgets",
      "Chaos Monkey",
      "Fault Injection",
      "Circuit Breaker",
      "Rate Limiting",
      "Throttling",
      "Load Balancing",
      "Auto-scaling",
      "Blue-Green Deployment",
      "Canary Releases",
      "Feature Toggles",
      "Dark Launching",
      "A/B Testing",
      "Multivariate Testing",
      "User Acceptance Testing",
      "Usability Testing",
      "Accessibility Testing",
      "Cross-Browser Testing",
      "Cross-Platform Testing",
      "Mobile Testing",
      "Responsive Testing",
      "Visual Regression Testing",
      "Snapshot Testing",
      "Mutation Testing",
      "Fuzzing",
      "Property-Based Testing",
      "Contract Testing",
      "Consumer-Driven Contract Testing",
      "API Testing",
      "GraphQL Testing",
      "REST API Testing",
      "SOAP API Testing",
      "Microservices Testing",
      "Integration Testing",
      "End-to-End Testing",
      "Acceptance Testing",
      "Behavior-Driven Development",
      "Gherkin",
      "Cucumber",
      "Selenium",
      "Cypress",
      "Puppeteer",
      "Playwright",
      "WebdriverIO",
      "TestCafe",
      "Jest",
      "Mocha",
      "Jasmine",
      "Karma",
      "RSpec",
      "PHPUnit",
      "JUnit",
      "NUnit",
      "xUnit",
      "PyTest",
      "Mockito",
      "Sinon",
      "WireMock",
      "VCR",
      "Pact",
      "Postman",
      "SoapUI",
      "Apache JMeter",
      "Gatling",
      "Locust",
      "K6",
      "Artillery",
      "Lighthouse",
      "WebPageTest",
      "GTmetrix",
      "PageSpeed Insights",
      "Chrome DevTools",
      "Firefox Developer Tools",
      "Safari Web Inspector",
      "Edge DevTools",
      "React DevTools",
      "Redux DevTools",
      "Vue DevTools",
      "Angular DevTools",
      "Webpack Bundle Analyzer",
      "Source Maps",
      "Browser Extensions",
      "Progressive Web Apps",
      "Service Workers",
      "Web Workers",
      "IndexedDB",
      "LocalStorage",
      "SessionStorage",
      "Cookies",
      "Web APIs",
      "Fetch API",
      "Geolocation API",
      "Web Notifications API",
      "Web Speech API",
      "Web Audio API",
      "WebRTC",
      "WebGL",
      "WebGPU",
      "WebXR",
      "WebNFC",
      "WebUSB",
      "WebBluetooth",
      "WebAuthn",
      "Web Crypto API",
      "Internationalization API",
      "Intl",
      "i18n",
      "l10n",
      "RTL Support",
      "Accessibility",
      "ARIA",
      "Screen Readers",
      "Keyboard Navigation",
      "Color Contrast",
      "Font Sizing",
      "Responsive Images",
      "Lazy Loading",
      "Infinite Scrolling",
      "Virtual Scrolling",
      "Pagination",
      "State Management",
      "Redux",
      "MobX",
      "Vuex",
      "NgRx",
      "Recoil",
      "Jotai",
      "XState",
      "RxJS",
      "Observables",
      "Reactive Programming",
      "Functional Programming",
      "Immutability",
      "Pure Functions",
      "Higher-Order Functions",
      "Closures",
      "Currying",
      "Memoization",
      "Recursion",
      "Generators",
      "Iterators",
      "Async/Await",
      "Promises",
      "Event Loop",
      "Garbage Collection",
      "Memory Management",
      "Performance Profiling",
      "Code Splitting",
      "Tree Shaking",
      "Dead Code Elimination",
      "Hot Module Replacement",
      "Server-Side Rendering",
      "Static Site Generation",
      "Jamstack",
      "Headless CMS",
      "Content Management Systems",
      "WordPress",
      "Drupal",
      "Joomla",
      "Ghost",
      "Strapi",
      "Contentful",
      "Sanity",
      "Prismic",
      "GraphCMS",
      "DatoCMS",
    ],
  },
  socials: [
    {
      href: "https://www.linkedin.com/in/lorenzopalaia/",
      icon: <Linkedin className="text-muted-foreground hover:text-primary" />,
    },
    {
      href: "https://github.com/lorenzopalaia",
      icon: <Github className="text-muted-foreground hover:text-primary" />,
    },
    {
      href: "mailto:lorenzopalaia53@gmail.com",
      icon: <Mail className="text-muted-foreground hover:text-primary" />,
    },
  ],
  work: [
    {
      title: "Computer Vision Software Engineer",
      company: "Sapienza Flight Team",
      startDate: "Sep 2021",
      endDate: "Oct 2022",
      items: [
        <p key={1}>
          Implemented the object detection and terrain mapping systems of a UAV,
          trained <span className="font-bold">YOLOv5/EfficientNet</span> models
          with custom datasets
        </p>,
        <p key={2}>
          Designed the{" "}
          <span className="font-bold">communication protocols</span> between UAV
          and Ground Station from scratch via endpoints using Flask,
          restructured the labeling GUI
        </p>,
        <p key={3}>
          Worked in a subteam of 5 and collaborated frequently with 60 people in
          other sumteams, migrated the entire Flight Team workflow to Slack
        </p>,
        <p key={4}>
          Earned a <span className="font-bold">15th</span> position out of 71
          entries for the Technical Design Paper in the AUVSI SUAS competition
        </p>,
      ],
      href: "https://www.sasa-aerospace.it/flight-team/",
      img: "/flightteam.png",
    },
    {
      title: "Software Developer",
      company: "Freelance",
      startDate: "2019",
      endDate: "Present",
      items: [
        <p key={1}>
          Developed websites and applications for more than{" "}
          <span className="font-bold">5</span> private and corporate clients
          including landing pages, bots and trackers,
        </p>,
      ],
      href: "https://github.com/lorenzopalaia",
      img: "/github.png",
      links: [
        {
          title: "GitHub",
          href: "https://github.com/lorenzopalaia",
        },
      ],
    },
  ],
  education: [
    {
      title: "BsC in Computer and Automatic Engineering",
      company: "Sapienza University of Rome",
      startDate: "",
      endDate: "Mar 2024",
      items: [
        <div key={1}>
          Best Marks:
          <ul className="ml-4 list-outside list-disc">
            <li>
              Operative Systems, Functional Programming, Programming Techniques{" "}
              <span className="font-bold">4.0 GPA with honors</span>
            </li>
            <li>
              Computer Architecture, Computer Networks, Databases, Software
              Engineering <span className="font-bold">4.0 GPA</span>
            </li>
          </ul>
        </div>,
      ],
      href: "https://www.uniroma1.it/it/",
      img: "/sapienza.jpeg",
      links: [
        {
          title: "Thesis Paper",
          href: "/thesis.pdf",
        },
        {
          title: "Thesis Project",
          href: "https://github.com/lorenzopalaia/Neural-Style-Transfer-and-Genre-Classification",
        },
      ],
    },
  ],
  extra: [
    {
      title: "Boolean Data Week",
      company: "Boolean Careers",
      startDate: "",
      endDate: "Nov 2023",
      href: "https://boolean.careers",
      img: "/boolean.png",
    },
    {
      title: "<Code.Your.Future> AI Hackathon",
      company: "Randstad",
      startDate: "",
      endDate: "Mar 2023",
      items: [
        <p key={1}>
          Led the development of a{" "}
          <span className="font-bold">job description classifier</span> in a
          team of 5 using TensorFlow during a 4-hour challenge
        </p>,
        <p key={2}>
          Secured the <span className="font-bold">2nd</span> spot out of 8
          contenders, reached an F1 score of 75%, explored both Bag of Words and
          Word2Vec solutions
        </p>,
      ],
      href: "https://www.randstad.it/",
      img: "/randstad.png",
      links: [
        {
          title: "Submission",
          href: "https://github.com/lorenzopalaia/Randstad-AI-Hackathon",
        },
      ],
    },
  ],
  skills: [
    "React",
    "Next.js",
    "Tailwind",
    "Node.js",
    "Git",
    "Python",
    "C",
    "Java",
    "Linux",
    "Bash",
    "Arduino",
  ],
  projects: [
    {
      name: "Alfa Impianti S.r.l.",
      description: "Developed a corporate website for Alfa Impianti S.r.l.",
      languages: ["Javascript", "HTML", "CSS"],
      img: "",
      html_url: "https://alfa-impiantisrl.it",
      updated_at: "2020-10-01T00:00:00Z",
    },
  ],
  featuredProjects: [
    // ! github projects
    "Neural-Style-Transfer-and-Genre-Classification",
    "Arduino-Oscilloscope",
    "Blocktracr",
    "Euro-Hackathons",
    // ! other projects
  ],
};
