import {
  SiTypescript,
  SiGit,
  SiCss3,
  SiJavascript,
  SiJupyter,
  SiC,
  SiMake,
  SiMarkdown,
  SiMdx,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiVuedotjs,
  SiHtml5,
  SiCplusplus,
  SiPython,
  SiNodedotjs,
  SiLinux,
  SiArduino,
  SiGnubash,
  SiSupabase,
} from "react-icons/si";
import { FaJava, FaTerminal } from "react-icons/fa";

export const email = "lorenzopalaia53@gmail.com";

export const config = {
  settings: {
    fallbackImage:
      "https://raw.githubusercontent.com/lorenzopalaia/Repo-Template/main/repo_assets/preview.png",
    keywords: [
      "software engineer",
      "software engineer software",
      "engineer software engineer",
      "software engineer software engineer",
      "software engineer engineer",
      "software software engineer",
      "engineer in software",
      "software developer",
      "software developer software",
      "software developer software developer",
      "software devs",
      "software developer developer",
      "engineer of systems",
      "computer engineer",
      "computer engineering engineering",
      "computer of engineering",
      "engineer in finance",
      "software on the computer",
      "computer with software",
      "computer software computer",
      "computer software in computer",
      "vision engineer",
      "station engineer",
      "freelance developer",
      "ai software engineer",
      "artificial intelligence software engineer",
      "software engg jobs",
      "software programer",
      "software programs",
      "software designer",
      "computer vision engineer",
      "software designers",
      "freelance computer programming",
      "program freelance",
      "work on software",
      "freelance software developer",
      "software development engineer",
      "freelance software programmer",
      "freelance software designer",
      "software dev engineer",
      "software techie",
      "full stack developer what is",
      "graduate software engineer",
      "computer developer",
      "full stack software developer",
      "developer engineer",
      "engineer ai",
      "engineering developer",
      "systems engineering it",
      "italy software engineer",
      "grad software engineer",
      "freelance software engineer",
      "freelance engineer",
      "engineering software developer",
      "software developer and software engineer",
      "software engineer software developer",
      "computer and engineering",
      "application developer freelance",
      "engineer work",
      "freelance work programming",
      "software engineer italy",
      "engineer team",
      "software engineering italy",
      "computer software engineer",
      "software freelance",
      "freelance full stack developer",
      "blockchain engineer",
      "ai software developer",
      "full stack software engineer",
      "software design engineer",
      "artificial intelligence software developer",
      "difference between software engineer and software developer",
      "freelance fullstack",
      "artificial intelligence freelance",
      "engineer computer systems",
      "difference between a software developer and software engineer",
      "education engineer",
      "engineer technical",
      "mapping engineer",
      "software engineer for data science",
      "systems engineering in software engineering",
      "it software engineer",
      "computer software developer",
      "programming engineer",
      "blockchain software engineer",
      "be a software engineer",
      "it software developer",
      "blockchain software developer",
      "crypto software engineer",
      "finance software engineer",
      "a software engineer",
      "crypto software developer",
      "software engineer i",
      "graduate software developer",
      "about software engineering",
      "software engineer work",
      "freelance software developer sites",
      "software application developer",
      "software engineer developer",
      "be software engineering",
      "crypto engineer",
      "software engineer education",
      "the software developer",
      "computer programming engineer",
      "freelance software dev",
      "computer vision software engineer",
      "a software developer",
      "independent software developer",
      "software engineer skills",
      "be a software developer",
      "software developer computer science",
      "freelance software developer near me",
      "software ai engineer",
      "software engineer is",
      "computer science software engineering",
      "flight software engineer",
      "freelance software developer website",
      "traveling software engineer",
      "software engineer blockchain",
      "it and software engineering",
      "computer science and software engineering",
      "computer vision developer",
      "systems software engineer",
      "freelance work for software engineer",
      "systems software developer",
      "software developer team",
      "software engineer crypto",
      "programming developer",
      "the software engineer",
      "qualifications for software engineer",
      "software engineer mein",
      "freelance software developer work",
      "for software engineer",
      "software engineer at",
      "as a software engineer",
      "apa itu software engineer",
      "programming software engineering",
      "full stack developer software engineer",
      "computer engineering and software engineering",
      "software engineer team",
      "as software engineer",
      "freelance systems engineer",
      "data software engineer",
      "independent software engineer",
      "software engineer applications",
      "software developer ai",
      "ingenieur software",
      "computer software engineer near me",
      "software developer to software engineer",
      "freelance software work",
      "software developer work",
      "software it engineer",
      "freelance computer engineer",
      "vision software engineer",
      "software engineer position",
      "computer for engineer",
      "software engineer full stack developer",
      "software injiniyar",
      "software researcher",
      "work software engineer",
      "it computer engineering",
      "software engineer from scratch",
      "it computer software",
      "software developer finance",
      "freelance it developer",
      "software developer blockchain",
      "software graduate",
      "freelance dev work",
      "software developer in",
      "software engineer freelance work",
      "software engineer 5",
      "software engineer to finance",
      "software developer at",
      "software developer what is it",
      "software developer is",
      "software developer i",
      "for software developer",
      "software developer what is",
      "software engineer and developer",
      "software engineer university graduate",
      "it developer engineer",
      "uav software engineer",
      "traveling engineer",
      "systems developer",
      "full stack developer software",
      "network software engineer",
      "finance and software engineering",
      "freelance computer",
      "computer programming and software engineering",
      "apa itu software developer",
      "full stack developer and software engineer",
      "full stack developer is a software engineer",
      "software development engineer skills",
      "full stack developer engineer",
      "computer applications engineer",
      "from full stack developer to software engineer",
      "passionate software engineer",
      "data science software engineer",
      "developer applications",
      "data science and software engineering",
      "be computer engineer",
      "computer engineering and artificial intelligence",
      "education software developer",
      "about computer engineer",
      "a computer engineer",
      "technical software engineer",
      "it applications engineer",
      "software applications in software engineering",
      "i work as a software engineer",
      "software dev team",
      "computer engineer work",
      "technical developer",
      "freelance work for programmers",
      "between software",
      "computer engineer education",
      "the work of software engineer",
      "a full stack developer",
      "software engineer and full stack developer",
      "sep software engineer",
      "systems engineer i",
      "engineering programming software",
      "difference between full stack developer and software engineer",
      "software engineer profile",
      "software developer in italy",
      "blockchain in engineering",
      "vision systems engineer",
      "software engineer dev",
      "engineer 5",
      "passionate software developer",
      "software engineer in computer science",
      "working as a developer",
      "software engineer data science",
      "work engineer",
      "artificial intelligence and computer engineering",
      "engineering freelance work",
      "software developer systems software",
      "systems engineering what is it",
      "full stack developer and software developer",
      "engineer position",
      "engineer communication",
      "difference of software developer and software engineer",
      "difference between it engineer and software engineer",
      "software development engineer i",
      "computer software engineer requirements",
      "applications systems",
      "work as engineer",
      "crypto engineers",
      "data software developer",
      "working as a software developer",
      "engineering design freelance",
      "software private",
      "it systems developer",
      "computer science of software engineering",
      "programming and engineering",
      "software developer italy",
      "computer engineering and programming",
      "computer science in software engineering",
      "software developer software engineer difference between",
      "the difference between software developer and software engineer",
      "engineering computer programming",
      "software engineering in data science",
      "developer systems",
      "software product developer",
      "5 software of computer",
      "5x engineer",
      "applications systems engineer",
      "backend engineer work",
      "becoming a freelance software developer",
      "computer engineer profile",
      "computer engineer skills",
      "computer engineering and software engineering same",
      "computer engineering in",
      "computer engineering it",
      "computer freelance work",
      "computer science to finance",
      "computer software work",
      "computer systems and engineering",
      "corporate software engineer",
      "crypto programmer",
      "data engineer and software engineer",
      "data engineer software engineer",
      "data engineer to software engineer",
      "data science in software engineering",
      "data science to software engineer",
      "design engineering in software engineering",
      "developer at work",
      "difference between a software engineer and developer",
      "difference between computer engineer and software engineer",
      "difference between developer and software engineer",
      "difference between software engineer and software development engineer",
      "difference between software engineer and software programmer",
      "difference between systems engineer and software engineer",
      "engineer applications",
      "engineer workflow",
      "engineering software skills",
      "for computer engineering",
      "freelance blockchain",
      "freelance crypto",
      "from data engineer to software engineer",
      "from data science to software engineering",
      "gui software engineer",
      "network engineer to software engineer",
      "profile for software engineer",
      "protocol engineer",
      "qualification for computer engineer",
      "software computer science",
      "software corporate",
      "software developer and software engineer are same",
      "software development engineer role",
      "software engineer and software developer are same",
      "software engineer data engineer",
      "software engineer posting",
      "the difference between software engineer and software developer",
      "work in software",
      "work of an it engineer",
      "work software developer",
      "work with software",
    ],
  },
  about: {
    name: "Lorenzo Palaia",
    title: "Software Engineer | Computer and Automation Engineering Graduate",
    description:
      "Crypto enthusiast, passionate about programming, artificial intelligence, blockchain, finance and traveling. Computer and Automation Engineering graduate at Sapienza University of Rome. Currently working as a freelance fullstack developer.",
    location: "Rome, Italy",
  },
  socials: [
    {
      name: "LinkedIn",
      href: "https://www.linkedin.com/in/lorenzopalaia/",
    },
    {
      name: "GitHub",
      href: "https://github.com/lorenzopalaia",
    },
    {
      name: "X",
      href: "https://x.com/lorenzopalaia",
    },
    {
      name: "Email",
      href: `mailto:${email}`,
    },
    {
      name: "Book a Meeting",
      href: "https://cal.com/lorenzopalaia/30min",
    },
  ],
  work: [
    {
      title: "Computer Vision Software Engineer",
      company: "Sapienza Flight Team",
      startDate: "Sep 2021",
      endDate: "Oct 2022",
      items: [
        "Developed object detection and terrain mapping systems for a UAV, training YOLOv5/EfficientNet models with custom datasets",
        "Designed and implemented communication protocols between UAV and Ground Station from scratch, developing a Flask‑based API and revamping the GUI",
        "Collaborated in a subteam of 5 within a 60‑member team, migrating the entire Flight Team workflow to Slack",
        "Earned a 15th position out of 71 entries for the Technical Design Paper in the AUVSI SUAS competition",
      ],
      href: "https://www.sasa-aerospace.it/flight-team/",
      img: "/images/flight-team.webp",
    },
    {
      title: "Software Developer",
      company: "Freelance",
      startDate: "2019",
      endDate: "Present",
      items: [
        "Engineered websites and applications for over 5 private and corporate clients, delivering solutions including landing pages, bots and trackers",
        "Collaborated with clients to analyze requirements, propose innovative ideas, document solutions and maintain software post‑release",
      ],
      href: "https://github.com/lorenzopalaia",
      img: "/images/github.webp",
      links: [
        {
          title: "GitHub",
          href: "https://github.com/lorenzopalaia",
        },
      ],
    },
  ],
  education: [
    {
      title: "BsC in Computer and Automation Engineering",
      company: "Sapienza University of Rome",
      startDate: "",
      endDate: "Mar 2024",
      items: [
        "Excelled in Operative Systems, Functional Programming, Programming Techniques (4.0 GPA with honors)",
        "Mastered Data Structures & Algorithms, Software Design, Parallel Computing, Electronics, Web Development (4.0 GPA)",
      ],
      href: "https://www.uniroma1.it/it/",
      img: "/images/sapienza.webp",
      links: [
        {
          title: "Thesis Paper",
          href: "/assets/thesis.pdf",
        },
        {
          title: "Thesis Project",
          href: "https://github.com/lorenzopalaia/Neural-Style-Transfer-and-Genre-Classification",
        },
      ],
    },
  ],
  extra: [
    {
      title: "Reply AI Music Contest",
      company: "Reply",
      startDate: "Apr 2025",
      endDate: "Jun 2025",
      items: [
        "Led the development of an AI-enhanced music and visual product in a team of 5, orchestrating workflow, timeline, and project management",
        "Set up Stable Audio Open with custom fine-tuning on electronic music for generating audio elements with accurate prompts",
        "Achieved semifinalist status among over 300 submissions",
      ],
      href: "https://challenges.reply.com/challenges/creative/ai-music-contest/home/",
      img: "/images/reply-ai-music-contest.png",
    },
    {
      title: "Open Source Contribution",
      company: "Tailark",
      startDate: "Mar 2025",
      endDate: "Apr 2025",
      items: [
        "Introduced two new blocks to enhance user experience and design consistency",
      ],
      id: 933694551,
      img: "/images/tailark.png",
    },
    {
      title: "Open Source Contribution",
      company: "Plane",
      startDate: "Mar 2025",
      endDate: "Apr 2025",
      items: [
        "Enhanced the authentication flow UI to improve clarity and user experience in environments with restricted access",
      ],
      id: 568098118,
      img: "/images/plane.webp",
    },
    {
      title: "Open Source Contribution",
      company: "JSON Crack",
      startDate: "Mar 2025",
      endDate: "Apr 2025",
      items: ["Fixed UI issues and improved accessibility"],
      id: 453717720,
      img: "/images/jsoncrack.webp",
    },
    {
      title: "Open Source Contribution",
      company: "Filepizza",
      startDate: "Mar 2025",
      endDate: "Apr 2025",
      items: [
        "Implemented multi-file selection functionality with sequential upload process, significantly enhancing user experience and workflow",
      ],
      id: 31341340,
      img: "/images/filepizza.webp",
    },
    {
      title: "Open Source Contribution",
      company: "tweakcn",
      startDate: "",
      endDate: "Mar 2025",
      items: [
        "Implemented a contrast accessibility checker with an optimized debounce mechanism to improve performance",
      ],
      id: 948174507,
      img: "/images/tweakcn.webp",
    },
    {
      title: "Open Source Contribution",
      company: "Origin UI",
      startDate: "",
      endDate: "Mar 2025",
      items: ["Refactored code to improve consistency and readability"],
      id: 872925629,
      img: "/images/origin-ui.webp",
    },
    {
      title: "Open Source Contribution",
      company: "Maybe Finance",
      startDate: "Jan 2024",
      endDate: "Feb 2024",
      items: [
        "Removed 22,000+ lines of legacy code to improve maintainability",
        "Identified and reported multiple UI issues including file download problems and behavior bugs",
      ],
      id: 737898780,
      img: "/images/maybe.webp",
    },
    {
      title: "<Code.Your.Future> AI Hackathon",
      company: "Randstad",
      startDate: "",
      endDate: "Mar 2023",
      items: [
        "Guided the development of a job description classification neural network in a team of 5 using TensorFlow within 4 hours",
        "Secured 2nd place, achieving an F1 score of 75% while experimenting with Bag of Words and Word2Vec approaches",
      ],
      href: "https://www.randstad.it/",
      img: "/images/randstad.webp",
      links: [
        {
          title: "Submission",
          href: "https://github.com/lorenzopalaia/Randstad-AI-Hackathon",
        },
      ],
    },
  ],
  skills: [
    "NextJS",
    "Typescript",
    "TailwindCSS",
    "React",
    "Vue",
    "Supabase",
    "NodeJS",
    "Git",
    "Python",
    "C",
    "Java",
    "Jupyter Notebook",
    "HTML",
    "CSS",
    "Javascript",
    "Linux",
    "Bash",
    "Markdown",
    "Arduino",
  ],
  projects: [
    {
      name: "Linktree",
      description: "Personal linktree for socials.",
      languages: ["NextJS", "React", "Typescript", "TailwindCSS", "Supabase"],
      img: "/",
      html_url: "",
      updated_at: "2024-10-07T00:00:00Z",
    },
    {
      name: "SitePulse",
      description: "Website monitoring tool for developers.",
      languages: ["NextJS", "React", "Typescript", "TailwindCSS", "Supabase"],
      img: "/",
      html_url: "",
      updated_at: "2024-10-01T00:00:00Z",
    },
    {
      name: "Alfa Impianti S.r.l.",
      description: "Developed a corporate website for Alfa Impianti S.r.l.",
      languages: ["Javascript", "HTML", "CSS"],
      img: "/",
      html_url: "https://www.alfa-impiantiservice.it/",
      updated_at: "2020-10-01T00:00:00Z",
    },
  ],
  additionalProjectsLanguages: {
    // * TailwindCSS automatically overwrites CSS if used in the same project
    Blocktracr: ["NextJS", "TailwindCSS", "React", "Supabase"],
    "lorenzopalaia.com": ["NextJS", "TailwindCSS", "React"],
    MediaShift: ["NextJS", "TailwindCSS", "React"],
    TurboClone: ["NextJS", "TailwindCSS", "React"],
    StackHound: ["NextJS", "TailwindCSS", "React"],
    "Euro-Hackathons": [
      "NextJS",
      "TailwindCSS",
      "React",
      "Supabase",
      "Markdown",
    ],
  },
  npmProjects: {
    // * Add npm packages here, they will be used to display npm downloads
    "Tailwind-Animations": "@lorenzopalaia/tailwind-animations",
    "Tailwind-Hero-Patterns": "@lorenzopalaia/tailwind-hero-patterns",
  },
  featuredProjects: [
    // * Add your projects here, they will be displayed in the featured section ordered as they are in the array
    // github projects
    "Blocktracr",
    "Neural-Style-Transfer-and-Genre-Classification",
    "Arduino-Oscilloscope",
    "Euro-Hackathons",
    "MediaShift",
    "Randstad-AI-Hackathon",
    // local projects
  ],
  includedForkRepos: [
    // * These repos are shown despite being forks
    "Randstad-AI-Hackathon",
  ],
};

export const languagesMap = {
  nodejs: {
    label: "Node.js",
    color: "2, 128, 0",
    icon: SiNodedotjs,
    description: "JavaScript runtime built on Chrome's V8 JavaScript engine.",
  },
  git: {
    label: "Git",
    color: "238, 118, 33",
    icon: SiGit,
    description: "Distributed version control system.",
  },
  linux: {
    label: "Linux",
    color: "128, 128, 128",
    icon: SiLinux,
    description: "Open-source Unix-like operating system.",
  },
  arduino: {
    label: "Arduino",
    color: "0, 148, 151",
    icon: SiArduino,
    description: "Open-source electronics platform.",
  },
  java: {
    label: "Java",
    color: "219, 83, 61",
    icon: FaJava,
    description: "Class-based, object-oriented programming language.",
  },
  bash: {
    label: "Bash",
    color: "128, 128, 128",
    icon: SiGnubash,
    description: "Unix shell and command language.",
  },
  shell: {
    label: "Shell",
    color: "128, 128, 128",
    icon: FaTerminal,
    description: "Command-line interface for Unix-based systems.",
  },
  supabase: {
    label: "Supabase",
    color: "127, 255, 3",
    icon: SiSupabase,
    description: "Open-source Firebase alternative.",
  },
  typescript: {
    label: "Typescript",
    color: "49, 120, 198",
    icon: SiTypescript,
    description: "Strongly typed superset of JavaScript.",
  },
  css: {
    label: "CSS",
    color: "21, 114, 182",
    icon: SiCss3,
    description: "Cascading Style Sheets.",
  },
  html: {
    label: "HTML",
    color: "227, 79, 38",
    icon: SiHtml5,
    description: "HyperText Markup Language.",
  },
  react: {
    label: "React",
    color: "97, 218, 251",
    icon: SiReact,
    description: "JavaScript library for building user interfaces.",
  },
  vue: {
    label: "Vue",
    color: "79, 192, 141",
    icon: SiVuedotjs,
    description: "Progressive JavaScript framework.",
  },
  javascript: {
    label: "Javascript",
    color: "247, 223, 30",
    icon: SiJavascript,
    description: "High-level, interpreted programming language.",
  },
  jupyternotebook: {
    label: "Jupyter",
    color: "243, 118, 38",
    icon: SiJupyter,
    description: "Open-source web application for interactive computing.",
  },
  c: {
    label: "C",
    color: "168, 185, 204",
    icon: SiC,
    description: "General-purpose, procedural computer programming language.",
  },
  makefile: {
    label: "Make",
    color: "0, 169, 143",
    icon: SiMake,
    description: "Build automation tool.",
  },
  python: {
    label: "Python",
    color: "55, 118, 171",
    icon: SiPython,
    description: "High-level, interpreted programming language.",
  },
  markdown: {
    label: "Markdown",
    color: "128, 128, 128",
    icon: SiMarkdown,
    description: "Lightweight markup language.",
  },
  mdx: {
    label: "MDX",
    color: "128, 128, 128",
    icon: SiMdx,
    description: "Markdown for the component era.",
  },
  nextjs: {
    label: "Next.js",
    color: "128, 128, 128",
    icon: SiNextdotjs,
    description: "React framework.",
  },
  tailwindcss: {
    label: "Tailwind CSS",
    color: "56, 178, 172",
    icon: SiTailwindcss,
    description: "Utility-first CSS framework.",
  },
  "c++": {
    label: "C++",
    color: "0, 89, 156",
    icon: SiCplusplus,
    description: "General-purpose programming language.",
  },
};

export const achievements = [
  {
    id: "featured",
    title: "Featured",
    description:
      "Ahoy, treasure hunter! You discovered the secret stash of projects! 🏆",
    points: 10,
    unlocked: false,
  },
  {
    id: "resume",
    title: "Resume",
    description:
      "Got curious, huh? You sneaked a peek into my career chronicles! 📜",
    points: 15,
    unlocked: false,
  },
  {
    id: "socials",
    title: "Socials",
    description: "Caught me on the interwebs! Let’s stay connected! 🌐",
    points: 15,
    unlocked: false,
  },
  {
    id: "thesis-paper",
    title: "Thesis Paper",
    description: "Brainiac alert! You explored my thesis masterpiece! 📚",
    points: 15,
    unlocked: false,
  },
  {
    id: "blog-post",
    title: "Blog Post",
    description: "Whoa, reader mode on! You dove into one of my blog posts! 📝",
    points: 15,
    unlocked: false,
  },
  {
    id: "post-like",
    title: "Post Like",
    description:
      "You hit the thumbs up! Thanks for liking one of my blog posts! 👍",
    points: 15,
    unlocked: false,
  },
  {
    id: "theme",
    title: "Theme Switch",
    description:
      "Dark side or light side? You toggled the theme like a pro! 🌓",
    points: 5,
    unlocked: false,
  },
  {
    id: "contact",
    title: "Contact",
    description: "Sliding into my inbox like a champ! You reached out! 🤝",
    points: 30,
    unlocked: false,
  },
  {
    id: "lead",
    title: "Blog Subscription",
    description: "You joined the blog squad! Welcome aboard! 🚀",
    points: 30,
    unlocked: false,
  },
  /*
  {
    id: "avatar",
    title: "Avatar",
    description: "Am I looking good or what? You hovered over my avatar! 👀",
    points: 5,
    unlocked: false,    
  },
  */
];
