import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import ThemeProvider from "@/components/ThemeProvider";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Overlay from "@/components/Overlay";
import DotPattern from "@/components/DotPattern";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const bricolageGrotesqueBold = localFont({
  src: "./fonts/BricolageGrotesqueBold.ttf",
  variable: "--font-bricolage-grotesque-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bricolageGrotesqueBold.variable} antialiased min-h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Overlay />
          <DotPattern>
            <Header />
            <div className="container mx-auto max-w-3xl px-8 relative z-10">
              <main>{children}</main>
              <Footer />
            </div>
          </DotPattern>
        </ThemeProvider>
      </body>
    </html>
  );
}
